### ISSUE TITLE
Snippets are Not Showing!

### ISSUE THREAD

**Issue by Asad-Muzammil** [therealjohn/UnityProjectTemplatesAndSnippets#2]
![Screenshot (3)](https://user-images.githubusercontent.com/38078814/111902768-d03bb700-8a60-11eb-8887-e31bd9c8eadd.png)
![Screenshot (4)](https://user-images.githubusercontent.com/38078814/111902770-d29e1100-8a60-11eb-8066-0eed9c0ffb91.png)
![Screenshot (5)](https://user-images.githubusercontent.com/38078814/111902772-d5006b00-8a60-11eb-837b-eede93791a0e.png)
![Screenshot (6)](https://user-images.githubusercontent.com/38078814/111902774-d6319800-8a60-11eb-8c81-f71496db85cf.png)
![Screenshot (7)](https://user-images.githubusercontent.com/38078814/111902779-d9c51f00-8a60-11eb-8e72-34edb17188b1.png)

**Comment by therealjohn** [comment]
I've started a PR to include this project in Visual Studio Tools for Unity so this extension won't be required anymore. That will include a fix for this issue too.
